# Generated by Django 4.1.1 on 2022-09-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0002_alter_experience_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='images/certificate.png', upload_to='')),
                ('org', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='images/cover.jpg', upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(default='')),
                ('link', models.URLField(default='https://github.com/AshuAhlawat')),
                ('completed', models.DateField()),
                ('on_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.experience')),
                ('skills', models.ManyToManyField(to='professional.skill')),
            ],
        ),
    ]
