# Generated by Django 4.1 on 2022-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='proof',
            field=models.ImageField(default='images/certificate.png', upload_to=''),
        ),
    ]
