# Generated by Django 4.1 on 2022-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='about',
            field=models.TextField(default="Hey i am enjoing coding, print('Hello Darkness, my old friend')"),
        ),
    ]
